### PR TITLE
Possibility

### PR DESCRIPTION
**Pull request by AceAttorneyMaster111**
The code in here should go in the /refs/bootstrap branch. When you are ready @Faahx7 feel free to merge this request.

### CODE REVIEW

**Comment by Faahx7** [comment]
maybe

**Comment by Faahx7** [comment]
ive added so much to Possibility that I don't want to merge it.

**Comment by AceAttorneyMaster111** [comment]
In this case, merging is just deleting the boilerplate template which is useless at this point. I still think you really should merge.

**Comment by Faahx7** [comment]
OI DONT RE OPEN IT

**Pull request closed without merging**
